#!/usr/bin/env python3
"""
alter_r_check.py -- Gate ALTER-R independent check script.

Written from scratch by the ALTER-R runner. It does not import, read or derive
from alter_check.py or alter_gate_check.py.

Exact arithmetic only: fractions.Fraction everywhere, plus a small exact
Q(sqrt2) class used for the one place sqrt2 genuinely appears (c/a = sqrt2).
No float takes part in any pass/fail decision.

Sections
  ENGINE     exact symmetry finder for decorated periodic point sets
  CHECK 1-4  the four obstruction checks of the original card, section 3.2
  CONTROL    positive control (rutile MnF2) + two negative controls
  NEARMISS   section-4 derivations for the patterns found in the corpus
             (added after the corpus search; see gate_ALTER_R_RESULT.md)

  CROSSCHECK non-gating comparison of every operation set with tabulated
             space-group operations (optional; needs spglib)

Run:  python3 alter_r_check.py                 exit code 0 iff every exact assertion holds.
      python3 alter_r_check.py --dump ops.json also writes every surviving-operation list as JSON.
"""
from fractions import Fraction as F
from itertools import product
import sys

# --------------------------------------------------------------------------
# Exact Q(sqrt2)
# --------------------------------------------------------------------------
class Q2:
    """p + q*sqrt(2), p and q rational. Exact."""
    __slots__ = ("p", "q")
    def __init__(s, p=0, q=0): s.p, s.q = F(p), F(q)
    def _c(s, o): return o if isinstance(o, Q2) else Q2(o, 0)
    def __add__(s, o): o = s._c(o); return Q2(s.p + o.p, s.q + o.q)
    __radd__ = __add__
    def __neg__(s): return Q2(-s.p, -s.q)
    def __sub__(s, o): return s + (-s._c(o))
    def __mul__(s, o):
        o = s._c(o); return Q2(s.p*o.p + 2*s.q*o.q, s.p*o.q + s.q*o.p)
    __rmul__ = __mul__
    def __truediv__(s, o):
        o = s._c(o); n = o.p*o.p - 2*o.q*o.q
        return s * Q2(o.p/n, -o.q/n)
    def __eq__(s, o): o = s._c(o); return s.p == o.p and s.q == o.q
    def __hash__(s): return hash((s.p, s.q))
    def __repr__(s):
        if s.q == 0: return str(s.p)
        if s.p == 0: return f"{s.q}*sqrt2"
        return f"({s.p}+{s.q}*sqrt2)"
SQRT2 = Q2(0, 1)

# --------------------------------------------------------------------------
# ENGINE
# --------------------------------------------------------------------------
def fr(x): return x if isinstance(x, F) else F(x)
def vec(*a): return tuple(fr(x) for x in a)
def mod1(v): return tuple(x - (x.numerator // x.denominator) for x in v)
def vadd(a, b): return tuple(x + y for x, y in zip(a, b))
def vsub(a, b): return tuple(x - y for x, y in zip(a, b))
def mat(rows): return tuple(tuple(fr(x) for x in r) for r in rows)
def mv(M, v): return tuple(sum(M[i][j]*v[j] for j in range(3)) for i in range(3))
def mm(A, B): return tuple(tuple(sum(A[i][k]*B[k][j] for k in range(3)) for j in range(3)) for i in range(3))
def det(M):
    return (M[0][0]*(M[1][1]*M[2][2]-M[1][2]*M[2][1])
          - M[0][1]*(M[1][0]*M[2][2]-M[1][2]*M[2][0])
          + M[0][2]*(M[1][0]*M[2][1]-M[1][1]*M[2][0]))
def trace(M): return M[0][0]+M[1][1]+M[2][2]
def inv3(M):
    d = det(M)
    c = lambda i, j: (M[(i+1)%3][(j+1)%3]*M[(i+2)%3][(j+2)%3]
                      - M[(i+1)%3][(j+2)%3]*M[(i+2)%3][(j+1)%3])
    return tuple(tuple(c(j, i)/d for j in range(3)) for i in range(3))
I3 = mat([[1,0,0],[0,1,0],[0,0,1]])
MINUS_I3 = mat([[-1,0,0],[0,-1,0],[0,0,-1]])

def closure(gens):
    """Finite matrix group generated by gens."""
    G = {I3}; frontier = [I3]
    while frontier:
        new = []
        for g in frontier:
            for h in gens:
                x = mm(h, g)
                if x not in G:
                    G.add(x); new.append(x)
        frontier = new
    return sorted(G)

# Point groups, as integer matrices acting on fractional coordinates.
C4z = mat([[0,-1,0],[1,0,0],[0,0,1]])
C2x = mat([[1,0,0],[0,-1,0],[0,0,-1]])
D4H = closure([C4z, C2x, MINUS_I3])                     # tetragonal cell, order 16
OH  = closure([C4z, mat([[0,0,1],[1,0,0],[0,1,0]]), MINUS_I3])   # cubic cell, order 48
assert len(D4H) == 16 and len(OH) == 48

def op_type(R):
    """Geometric type of a point operation from (det, trace): basis independent."""
    d, t = det(R), trace(R)
    table = {(1,3):"1", (1,-1):"2", (1,0):"3", (1,1):"4", (1,2):"6",
             (-1,-3):"-1", (-1,1):"m", (-1,0):"-3", (-1,-1):"-4", (-1,-2):"-6"}
    return table[(int(d), int(t))]

def transform_label(lab, R):
    """How a site label transforms under the point part R.
       plain string         : scalar (species / occupancy)
       ('ps', s)            : pseudoscalar (handedness, chirality) -> det(R)*s
       ('ax', (x,y,z))      : axial vector (circulation, spin)     -> det(R)*R v
       ('pv', (x,y,z))      : polar vector                         -> R v
       ('dir', (x,y,z))     : director (headless axis)             -> +-R v, canonical sign
       A tuple label may carry extra trailing fields, kept unchanged."""
    if isinstance(lab, str): return lab
    kind = lab[0]
    if kind == "ps": return ("ps", det(R)*lab[1]) + tuple(lab[2:])
    if kind == "ax": return ("ax", tuple(det(R)*x for x in mv(R, lab[1]))) + tuple(lab[2:])
    if kind == "pv": return ("pv", mv(R, lab[1])) + tuple(lab[2:])
    if kind == "dir":
        w = mv(R, lab[1])
        for x in w:
            if x != 0:
                if x < 0: w = tuple(-y for y in w)
                break
        return ("dir", w) + tuple(lab[2:])
    raise ValueError(kind)

class Structure:
    """Periodic decorated point set in a conventional cell.
       centrings: centring vectors (always including 0); lattice = Z^3 + centrings.
       sites: iterable of (position, label); expanded by centrings, reduced mod 1."""
    def __init__(self, centrings, sites, name=""):
        self.name = name
        self.cent = sorted({mod1(vec(*c)) for c in centrings} | {vec(0,0,0)})
        pts = {}
        for p, lab in sites:
            for c in self.cent:
                q = mod1(vadd(vec(*p), c))
                if q in pts and pts[q] != lab:
                    raise ValueError(f"two labels on one site {q}: {pts[q]} vs {lab}")
                pts[q] = lab
        self.pts = pts
    def canon_t(self, t):
        return min(mod1(vadd(t, c)) for c in self.translation_cosets())
    def maps_to(self, R, t, other=None):
        """Does (R|t) map self onto other (default self), labels included?"""
        tgt = (other or self).pts
        if len(tgt) != len(self.pts): return False
        for p, lab in self.pts.items():
            q = mod1(vadd(mv(R, p), t))
            if tgt.get(q, None) != transform_label(lab, R): return False
        return True
    def translation_cosets(self):
        """The TRUE translation group of this decorated structure, as cosets modulo Z^3:
           the input centrings plus any further pure translation the structure happens to have."""
        if getattr(self, "_tc", None) is None:
            p0, lab0 = next(iter(self.pts.items()))
            tc = set()
            for q, lq in self.pts.items():
                if lq != lab0: continue
                t = mod1(vsub(q, p0))
                if self.maps_to(I3, t): tc.add(t)
            self._tc = tc
        return self._tc
    def lattice_compatible(self, R):
        """A point operation can only belong to the symmetry group if it maps the true translation
           lattice into itself. Without this test a rational (non-integer) matrix -- e.g. a cubic
           3-fold written in the tetragonal frame -- would be 'verified' against one cell only and
           wrongly accepted for a structure whose lattice it does not preserve."""
        tc = self.translation_cosets()
        gens = [vec(1,0,0), vec(0,1,0), vec(0,0,1)] + [t for t in tc if any(x != 0 for x in t)]
        return all(mod1(mv(R, g)) in tc for g in gens)
    def ops_onto(self, pointops, other=None):
        """All (R|t), t modulo the lattice, mapping self onto other (default self)."""
        o = other or self
        p0, lab0 = min(self.pts.items(), key=lambda kv: sum(1 for l in self.pts.values() if l == kv[1]))
        found = set()
        for R in pointops:
            if not self.lattice_compatible(R): continue
            l0 = transform_label(lab0, R); Rp = mv(R, p0)
            for q, lq in o.pts.items():
                if lq != l0: continue
                t = self.canon_t(vsub(q, Rp))
                if (R, t) in found: continue
                if self.maps_to(R, t, o): found.add((R, t))
        return sorted(found)
    def is_lattice_vector(self, v):
        return any(all(x.denominator == 1 for x in vsub(v, c)) for c in self.cent)

def order_of(R):
    n, M = 1, R
    while M != I3: M = mm(M, R); n += 1
    return n

def in_integer_span(gens, target):
    """Exact test: is the rational vector `target` an INTEGER combination of the rational vectors `gens`?
       All vectors are scaled to integers by a common denominator, the generators are brought to row-echelon
       form by unimodular integer row operations (Euclid), and the target is reduced against the pivots.
       No search bound is involved."""
    from math import gcd
    den = 1
    for v in list(gens) + [target]:
        for x in v: den = den * x.denominator // gcd(den, x.denominator)
    rows = [[int(x * den) for x in v] for v in gens if any(x != 0 for x in v)]
    tgt = [int(x * den) for x in target]
    basis = []                                   # echelon rows as (pivot column, row)
    for col in range(3):
        while True:                              # Euclid on column `col` among the remaining rows
            nz = [r for r in rows if r[col] != 0]
            if len(nz) <= 1: break
            nz.sort(key=lambda r: abs(r[col])); p = nz[0]
            for r in nz[1:]:
                q = r[col] // p[col]
                for k in range(3): r[k] -= q * p[k]
        nz = [r for r in rows if r[col] != 0]
        if nz:
            basis.append((col, nz[0])); rows = [r for r in rows if r is not nz[0]]
    for col, p in basis:
        if tgt[col] % p[col] != 0: return False
        q = tgt[col] // p[col]
        tgt = [a - q * b for a, b in zip(tgt, p)]
    return all(x == 0 for x in tgt)

def is_nonsymmorphic_op(S, R, t):
    """True iff (R|t+l) is a screw/glide for EVERY lattice vector l of the structure's true lattice, i.e. the
       operation has an intrinsic fractional translation that no choice of lattice representative removes.
       With P = (1/n) sum_k R^k the projector onto the R-invariant subspace, (R|t+l) has a fixed point iff
       P(t+l) = 0. So the operation is point-type for some representative iff -P t lies in the integer span of
       {P g : g a generator of the lattice}; this is decided exactly by in_integer_span (no bounded search)."""
    n = order_of(R)
    acc, M = [[F(0)]*3 for _ in range(3)], I3
    for _ in range(n):
        acc = [[acc[i][j] + M[i][j] for j in range(3)] for i in range(3)]
        M = mm(M, R)
    P = tuple(tuple(x / n for x in row) for row in acc)
    gens = [vec(1,0,0), vec(0,1,0), vec(0,0,1)] + [c for c in S.translation_cosets() if any(x != 0 for x in c)]
    return not in_integer_span([mv(P, g) for g in gens], tuple(-x for x in mv(P, t)))

def fmt_v(v): return "(" + ",".join(str(x) for x in v) + ")"
def fmt_op(S, R, t):
    ty = op_type(R)
    tag = ""
    if ty not in ("1", "-1"):
        tag = " [screw/glide]" if is_nonsymmorphic_op(S, R, t) else ""
    elif ty == "1" and not all(x == 0 for x in t):
        tag = " [pure translation]"
    rows = ";".join(" ".join(f"{int(x):2d}" if x.denominator == 1 else str(x) for x in r) for r in R)
    return f"{ty:>3} | t={fmt_v(t)}{tag}   R=[{rows}]"

def triplet(R, t):
    """Coordinate-triplet form of (R|t), as in International Tables: e.g. -y+1/2,x+1/2,z+1/2."""
    out = []
    for i in range(3):
        term = ""
        for j, ax in enumerate("xyz"):
            c = R[i][j]
            if c == 0: continue
            mag = "" if abs(c) == 1 else (str(abs(c)) + "*")
            term += ("-" if c < 0 else ("+" if term else "")) + mag + ax
        if t[i] != 0: term += ("+" if t[i] > 0 else "") + str(t[i])
        out.append(term or "0")
    return ",".join(out)

OPSETS = {}          # name -> dict(frame=..., ops=[triplets]) ; filled by describe(), dumped with --dump

PG_SIGNATURES = {
    "C1 (1)": {"1":1}, "Ci (-1)": {"1":1,"-1":1}, "C2 (2)": {"1":1,"2":1}, "Cs (m)": {"1":1,"m":1},
    "C2h (2/m)": {"1":1,"2":1,"-1":1,"m":1}, "D2 (222)": {"1":1,"2":3}, "C2v (mm2)": {"1":1,"2":1,"m":2},
    "D2h (mmm)": {"1":1,"2":3,"-1":1,"m":3}, "C4 (4)": {"1":1,"2":1,"4":2}, "S4 (-4)": {"1":1,"2":1,"-4":2},
    "C4h (4/m)": {"1":1,"2":1,"4":2,"-1":1,"m":1,"-4":2}, "D4 (422)": {"1":1,"2":5,"4":2},
    "C4v (4mm)": {"1":1,"2":1,"4":2,"m":4}, "D2d (-42m)": {"1":1,"2":3,"m":2,"-4":2},
    "D4h (4/mmm)": {"1":1,"2":5,"4":2,"-1":1,"m":5,"-4":2},
    "C3 (3)": {"1":1,"3":2}, "S6 (-3)": {"1":1,"3":2,"-1":1,"-3":2}, "D3 (32)": {"1":1,"2":3,"3":2},
    "C3v (3m)": {"1":1,"3":2,"m":3}, "D3d (-3m)": {"1":1,"2":3,"3":2,"-1":1,"m":3,"-3":2},
    "T (23)": {"1":1,"2":3,"3":8}, "Th (m-3)": {"1":1,"2":3,"3":8,"-1":1,"m":3,"-3":8},
    "O (432)": {"1":1,"2":9,"3":8,"4":6}, "Td (-43m)": {"1":1,"2":3,"3":8,"m":6,"-4":6},
    "Oh (m-3m)": {"1":1,"2":9,"3":8,"4":6,"-1":1,"m":9,"-3":8,"-4":6},
}
def point_group(ops):
    Rs = sorted({R for R, _ in ops}); sig = {}
    for R in Rs: sig[op_type(R)] = sig.get(op_type(R), 0) + 1
    for name, s in PG_SIGNATURES.items():
        if s == sig: return name, len(Rs)
    return f"unlisted {sig}", len(Rs)

def translations(ops):
    """Pure translations in the op list (R = identity), modulo the input lattice."""
    return sorted(t for R, t in ops if R == I3)

def exchange_analysis(name, cent, host_sites, A_sites, B_sites, pointops, verbose=True):
    """The altermagnet test, stated crystallographically.
       Build X_A = host + A marked 'S1' + B marked 'S2' (sublattices distinguishable)
       and X_B = host + A marked 'S2' + B marked 'S1' (sublattices exchanged).
       Operations mapping X_A -> X_A keep each sublattice; X_A -> X_B exchange them.
       Site labels given by the corpus (orientation, handedness...) are carried in
       the label tuple and transform properly under the operation.
       (a) exchanged by a pure lattice translation?   -> degenerate
       (b) exchanged by inversion about some point?    -> degenerate
       (c) exchanged ONLY by rotations / rotoinversions (with or without fractional
           translation), none of type (a) or (b)       -> altermagnetic-allowed."""
    def mark(sites, m):
        out = []
        for p, lab in sites:
            out.append((p, (lab + (m,)) if isinstance(lab, tuple) else f"{lab}#{m}"))
        return out
    XA = Structure(cent, list(host_sites) + mark(A_sites, "S1") + mark(B_sites, "S2"), name)
    XB = Structure(cent, list(host_sites) + mark(A_sites, "S2") + mark(B_sites, "S1"), name)
    keep = XA.ops_onto(pointops)
    swap = XA.ops_onto(pointops, XB)
    a = [(R, t) for R, t in swap if R == I3]
    b = [(R, t) for R, t in swap if R == MINUS_I3]
    c = [(R, t) for R, t in swap if R not in (I3, MINUS_I3)]
    verdict = ("NO EXCHANGE SYMMETRY (sublattices inequivalent: ferri-type, not compensated by symmetry)"
               if not swap else
               "DEGENERATE (translation)" if a else
               "DEGENERATE (inversion)" if b else
               "ALTERMAGNETIC-ALLOWED (rotation/screw/glide only)")
    if verbose:
        print(f"  [{name}]")
        print(f"    sublattice-preserving ops: {len(keep)}   sublattice-exchanging ops: {len(swap)}")
        print(f"    (a) exchanged by pure lattice translation : {'YES ' + fmt_v(a[0][1]) if a else 'NO'}")
        print(f"    (b) exchanged by inversion about a point  : {'YES, centre at ' + fmt_v(tuple(x/2 for x in b[0][1])) if b else 'NO'}")
        kinds = {}
        for R, t in c:
            k = op_type(R) + (" screw/glide" if is_nonsymmorphic_op(XA, R, t) else " point-type")
            kinds[k] = kinds.get(k, 0) + 1
        print(f"    (c) exchanged by rotation/rotoinversion   : {len(c)} ops {kinds if c else ''}".rstrip())
        print(f"    => {verdict}")
    return dict(keep=keep, swap=swap, a=a, b=b, c=c, verdict=verdict, XA=XA)

def full_group(name, cent, sites, pointops, verbose=True, list_ops=False):
    S = Structure(cent, sites, name)
    ops = S.ops_onto(pointops)
    pg, npg = point_group(ops)
    tr = [t for t in S.translation_cosets() if any(x != 0 for x in t) and t not in S.cent]
    nonsym = sum(1 for R, t in ops if R not in (I3,) and op_type(R) != "-1" and is_nonsymmorphic_op(S, R, t))
    if verbose:
        print(f"  [{name}] ops per input-lattice cell: {len(ops)}; point group {pg} (order {npg}); "
              f"extra pure translations beyond input lattice: {len(tr)} {[fmt_v(t) for t in tr]}; "
              f"ops that are screw/glide for every lattice representative: {nonsym}")
        if list_ops:
            for R, t in ops: print("      " + fmt_op(S, R, t))
    return dict(S=S, ops=ops, pg=pg, extra_tr=tr, nonsym=nonsym)

RESULTS = []
def check(label, cond):
    RESULTS.append((label, bool(cond)))
    print(f"  {'PASS' if cond else 'FAIL'}  {label}")
    return bool(cond)

# --------------------------------------------------------------------------
# Frames.  Tetragonal cell (a,a,c) with c/a = sqrt2; cubic FCC cell a_c = c.
# Cartesian (tetragonal frame): r = (a x, a y, sqrt2 a z).
# Cubic frame is the tetragonal frame rotated 45 deg about z.
# --------------------------------------------------------------------------
M_T2C = mat([[F(1,2), F(1,2), 0], [F(-1,2), F(1,2), 0], [0, 0, 1]])   # tetragonal frac -> cubic frac
M_C2T = inv3(M_T2C)
BCT = [vec(F(1,2), F(1,2), F(1,2))]                                   # body centring, tetragonal cell
FCC = [vec(0, F(1,2), F(1,2)), vec(F(1,2), 0, F(1,2)), vec(F(1,2), F(1,2), 0)]
OH_T = sorted({mm(M_C2T, mm(R, M_T2C)) for R in OH})                  # O_h written in tetragonal frac coords

def section(title): print("\n" + "="*78 + "\n" + title + "\n" + "="*78)

def check1():
    section("CHECK 1  BCT body-centring vector at c/a = sqrt2 is an FCC lattice vector")
    a = Q2(1); c = SQRT2 * a
    # Cartesian components of the BCT body-centring vector, tetragonal frame
    bc = (a*F(1,2), a*F(1,2), c*F(1,2))
    # rotate by -45 deg about z into the cubic frame: e1=(1,1,0)/sqrt2, e2=(-1,1,0)/sqrt2
    inv_s2 = Q2(1)/SQRT2
    X = (bc[0] + bc[1])*inv_s2; Y = (bc[1] - bc[0])*inv_s2; Z = bc[2]
    ac = SQRT2 * a                                       # cubic edge
    frac = (X/ac, Y/ac, Z/ac)
    print(f"  body-centring vector, Cartesian cubic frame, units of a: ({X}, {Y}, {Z})")
    print(f"  in units of a_c = sqrt2*a: {frac}")
    check("body-centring vector = a_c*(1/2, 0, 1/2): an FCC face-centring vector",
          frac == (Q2(F(1,2)), Q2(0), Q2(F(1,2))))
    check("c = a_c exactly (no sqrt2 residue)", c/ac == Q2(1))
    # same statement through the rational frame map
    check("rational frame map sends (1/2,1/2,1/2)_t to (1/2,0,1/2)_c",
          mv(M_T2C, BCT[0]) == vec(F(1,2), 0, F(1,2)))
    # whole lattices coincide: primitive Gram matrices (units a^2), c^2 = 2 a^2
    cc = (c*c)
    prim_t = [(Q2(1),Q2(0),Q2(0)), (Q2(0),Q2(1),Q2(0)), (Q2(F(1,2)),Q2(F(1,2)),c*F(1,2))]
    gram_t = [[sum((u[k]*v[k] for k in range(3)), Q2(0)) for v in prim_t] for u in prim_t]
    prim_c = [vec(F(1,2),F(-1,2),0), vec(F(1,2),F(1,2),0), vec(F(1,2),0,F(1,2))]   # images under frame map
    gram_c = [[Q2(2*sum(u[k]*v[k] for k in range(3))) for v in prim_c] for u in prim_c]  # a_c^2 = 2 a^2
    check("Gram matrix of BCT primitive vectors == Gram matrix of FCC primitive vectors", gram_t == gram_c)
    # lattice point group: 48 at sqrt2 (and the tetragonal frame only shows 16 of them as integer matrices)
    g_bct = full_group("bare spheres, tetragonal cell, D4h candidates", BCT, [(vec(0,0,0), "S")], D4H)
    g_fcc = full_group("bare spheres, tetragonal cell, O_h candidates (rational in this frame)", BCT, [(vec(0,0,0), "S")], OH_T)
    check("bare sphere lattice at c/a = sqrt2 has point group O_h (48 ops, symmorphic: Fm-3m, No. 225)",
          g_fcc["pg"].startswith("Oh") and len(g_fcc["ops"]) == 48 and g_fcc["nonsym"] == 0)
    check("theorem instance: corner and body-centre spheres are exchanged by a pure translation",
          exchange_analysis("bare BCT spheres", BCT[:0], [], [(vec(0,0,0), "S")], [(BCT[0], "S")], OH_T)["a"] != [])

def neighbours(p, spheres):
    best = {}
    for s in spheres:
        for l in product((-1, 0, 1), repeat=3):
            d = sum((a - b - c)**2 for a, b, c in zip(p, s, l))
            best.setdefault(d, 0); best[d] += 1
    dmin = min(best); return dmin, best[dmin]

def check2():
    section("CHECK 2  octahedral voids form an FCC translate of the sphere sites")
    S = Structure(FCC, [(vec(0,0,0), "S")])
    spheres = list(S.pts)
    oct_cell = [vec(F(1,2),F(1,2),F(1,2)), vec(F(1,2),0,0), vec(0,F(1,2),0), vec(0,0,F(1,2))]
    ok = True
    for p in oct_cell:
        d, n = neighbours(p, spheres)
        print(f"  oct candidate {fmt_v(p)}: nearest-sphere distance^2 = {d} a_c^2, coordination {n}")
        ok &= (d == F(1,4) and n == 6)
    check("each listed point is 6-coordinated at distance a_c/2 (an octahedral void)", ok)
    shifted = {mod1(vadd(p, vec(F(1,2),F(1,2),F(1,2)))) for p in spheres}
    check("oct void set == sphere set + (1/2,1/2,1/2)_c  (an FCC translate, itself FCC)", shifted == set(oct_cell))
    O = Structure(FCC, [(oct_cell[0], "O")])
    check("the oct set is closed under all FCC translations (one void per primitive cell)", set(O.pts) == set(oct_cell))
    g = full_group("oct voids alone", FCC, [(oct_cell[0], "O")], OH)
    check("oct voids alone: Bravais, O_h, symmorphic (no sublattice structure at all)",
          g["pg"].startswith("Oh") and g["nonsym"] == 0 and len(O.pts) == 4)
    # in the tetragonal cell the two oct voids per cell ARE corner/body-centre translates
    ot = sorted(mod1(mv(M_C2T, p)) for p in oct_cell)
    print(f"  oct voids in tetragonal fractional coords (mod 1): {sorted(set(ot))}")
    e = exchange_analysis("oct voids, tetragonal cell: (0,0,1/2) vs (1/2,1/2,0)", [], [],
                          [(vec(0,0,F(1,2)), "O")], [(vec(F(1,2),F(1,2),0), "O")], OH_T)
    check("the two oct voids of the BCT cell are exchanged by a pure translation -> degenerate", e["a"] != [])

def check3():
    section("CHECK 3  tetrahedral voids (1/4,1/4,1/4), (3/4,3/4,3/4): inversion, not translation")
    S = Structure(FCC, [(vec(0,0,0), "S")]); spheres = list(S.pts)
    tA, tB = vec(F(1,4),F(1,4),F(1,4)), vec(F(3,4),F(3,4),F(3,4))
    ok = True
    for p in (tA, tB):
        d, n = neighbours(p, spheres)
        print(f"  tet candidate {fmt_v(p)}: nearest-sphere distance^2 = {d} a_c^2, coordination {n}")
        ok &= (d == F(3,16) and n == 4)
    check("both points are 4-coordinated at distance sqrt3/4 a_c (tetrahedral voids)", ok)
    diff = vsub(tB, tA)
    check("T_B - T_A = (1/2,1/2,1/2)_c is NOT an FCC lattice vector", not S.is_lattice_vector(diff))
    e = exchange_analysis("tet voids with spheres as host", FCC, [(vec(0,0,0), "S")], [(tA, "T")], [(tB, "T")], OH)
    check("no pure translation exchanges the two tet sublattices", e["a"] == [])
    check("inversion (about a sphere site) DOES exchange them -> degenerate by inversion", e["b"] != [])
    check("verdict for undecorated tet voids is DEGENERATE (inversion)", e["verdict"].startswith("DEGENERATE (inversion)"))
    g = full_group("spheres + both tet sets, all tets alike", FCC, [(vec(0,0,0), "S"), (tA, "T"), (tB, "T")], OH)
    check("spheres + undecorated tets keep O_h (fluorite-type arrangement, Fm-3m)", g["pg"].startswith("Oh"))

def rutile_sites(u):
    metal_A = [(vec(0,0,0), "M")]
    metal_B = [(vec(F(1,2),F(1,2),F(1,2)), "M")]
    oxy = [(vec(u,u,0), "X"), (vec(-u,-u,0), "X"),
           (vec(F(1,2)+u, F(1,2)-u, F(1,2)), "X"), (vec(F(1,2)-u, F(1,2)+u, F(1,2)), "X")]
    return metal_A, metal_B, oxy

def rutile_tests(u, verbose=False):
    A, B, X = rutile_sites(u)
    S = Structure([], A + B + X)
    body = vec(F(1,2),F(1,2),F(1,2))
    Xonly = Structure([], X)
    trans_maps_X = Xonly.maps_to(I3, body)
    screw_maps_X = Xonly.maps_to(C4z, body)
    screw_maps_all = S.maps_to(C4z, body)
    return trans_maps_X, screw_maps_X, screw_maps_all

class Lin:
    """alpha + beta*u with u a free symbol: exact generic-u arithmetic mod 1."""
    def __init__(s, al, be): s.al, s.be = F(al), int(be)
    def __add__(s, o): return Lin(s.al + o.al, s.be + o.be)
    def __neg__(s): return Lin(-s.al, -s.be)
    def key(s): return (s.al - (s.al.numerator // s.al.denominator), s.be)

def check4():
    section("CHECK 4  rutile: body-centring translation fails on the anion set, 4_2 screw succeeds")
    # (i) symbolic, generic u: coordinates are alpha + beta*u; two such agree mod 1 for generic u
    #     iff beta equal and alpha equal mod 1.
    U = Lin(0, 1); Z = Lin(0, 0); H = Lin(F(1,2), 0)
    X = [(U, U, Z), (-U, -U, Z), (H + U, H + (-U), H), (H + (-U), H + U, H)]
    keyset = {tuple(c.key() for c in p) for p in X}
    trans = {tuple((c + H).key() for c in p) for p in X}
    screw = {((-p[1] + H).key(), (p[0] + H).key(), (p[2] + H).key()) for p in X}   # C4z:(x,y,z)->(-y,x,z)
    check("symbolic u: translation (1/2,1/2,1/2) does NOT map the anion set to itself", trans != keyset)
    check("symbolic u: screw {C4z | 1/2,1/2,1/2} DOES map the anion set to itself", screw == keyset)
    # (ii) where can the generic argument fail? translation needs (1/2+u,1/2+u,1/2) in the set:
    #      1/2+u = 1/2-u mod 1  <=>  2u integer  <=>  u in {0, 1/2} on [0,1/2].  Verify by exhaustive sweep.
    bad_t, bad_s, n = [], [], 0
    for q in range(2, 61):
        for p in range(1, q):
            u = F(p, q)
            if not (0 < u < F(1,2)) or u.denominator != q: continue
            n += 1
            t, s, s_all = rutile_tests(u)
            if t: bad_t.append(u)
            if not (s and s_all): bad_s.append(u)
    print(f"  rational sweep: {n} distinct u = p/q, 0<u<1/2, q<=60")
    check("sweep: translation fails for every u tested", bad_t == [])
    check("sweep: 4_2 screw succeeds for every u tested (anions and metals)", bad_s == [])
    X0 = Structure([], rutile_sites(F(0))[2])          # anions only, at the excluded endpoint u = 0
    t0 = X0.maps_to(I3, vec(F(1,2),F(1,2),F(1,2)))
    check("boundary sanity: at the excluded endpoint u = 0 (where the four anions collapse onto two points) the "
          "translation DOES succeed; negative control 1 below is the real evidence that the test can return 'translation'", t0)
    # the screw really is a screw, and really is 4_2
    A, B, Xs = rutile_sites(F(3,10))
    S = Structure([], A + B + Xs)
    body = vec(F(1,2),F(1,2),F(1,2))
    check("{C4z|1/2,1/2,1/2} is non-symmorphic for every lattice representative", is_nonsymmorphic_op(S, C4z, body))
    # (C4|t)^2 = (C2 | C4 t + t) = (C2 | (0,1,1)) -> pure lattice; (C4|t)^4 = (1 | (0,0,2)) ; intrinsic = 2/4 c
    t2 = vadd(mv(C4z, body), body)
    t4 = vadd(mv(mm(C4z, C4z), t2), t2)
    check("(screw)^4 = translation by 2c, i.e. pitch c/2 per quarter turn: a 4_2 axis", t4 == vec(0, 0, 2))

def control():
    section("CONTROL  known altermagnet on a body-centred tetragonal magnetic lattice")
    print("  Positive control: MnF2, rutile structure, P4_2/mnm (No. 136).")
    print("  Mn at 2a (0,0,0),(1/2,1/2,1/2) = a BCT magnetic lattice; F at 4f, u = 0.305 (61/200);")
    print("  collinear moments along c, antiparallel on the two Mn sites (Smejkal et al., PRX 12, 031042).")
    u = F(61, 200)
    A, B, X = rutile_sites(u)
    g = full_group("MnF2 non-magnetic crystal", [], A + B + X, D4H)
    # International Tables A, No. 136, general position: 1; 2 0,0,z; 4+/4-(0,0,1/2) [4_2 screws, 2 ops];
    # 2(0,1/2,0), 2(1/2,0,0) [2_1 screws, 2 ops]; 2 x,x,0; 2 x,-x,0; -1; m x,y,0; -4+/-4- [point-type];
    # n(1/2,0,1/2), n(0,1/2,1/2) [glides, 2 ops]; m x,x,z; m x,-x,z.   => 6 screw/glide operations.
    # (First run of this script asserted 8 here; that was the runner's miscount -- the two -4 operations
    #  exchange the sublattices but are point-type. Corrected to the tabulated 6; see result file, run log.)
    S0 = g["S"]; typ = {}
    for R, t in g["ops"]:
        if is_nonsymmorphic_op(S0, R, t): typ[op_type(R)] = typ.get(op_type(R), 0) + 1
    print(f"    screw/glide operations by type: {typ}")
    mz = [(R, t) for R, t in g["ops"] if R == mat([[1,0,0],[0,1,0],[0,0,-1]])][0]
    mx = [(R, t) for R, t in g["ops"] if R == mat([[-1,0,0],[0,1,0],[0,0,1]])][0]
    md = [(R, t) for R, t in g["ops"] if R == mat([[0,1,0],[1,0,0],[0,0,1]])][0]
    ok1 = check("control crystal: 16 ops, point group D4h, primitive (body centring is NOT a translation), "
                "6 screw/glide ops = {4: 2, 2: 2, m: 2}; plane normal to c is a mirror, normal to a is a glide, "
                "normal to [110] is a mirror -> P 4_2/m n m (No. 136)",
                len(g["ops"]) == 16 and g["pg"].startswith("D4h") and g["extra_tr"] == [] and g["nonsym"] == 6
                and typ == {"4": 2, "2": 2, "m": 2}
                and not is_nonsymmorphic_op(S0, *mz) and is_nonsymmorphic_op(S0, *mx)
                and not is_nonsymmorphic_op(S0, *md))
    e = exchange_analysis("MnF2: Mn(0,0,0) vs Mn(1/2,1/2,1/2)", [], X, A, B, D4H)
    ok2 = check("control: translation FAILS to exchange the Mn sublattices", e["a"] == [])
    ok3 = check("control: inversion FAILS to exchange the Mn sublattices", e["b"] == [])
    four = [(R, t) for R, t in e["c"] if op_type(R) == "4" and is_nonsymmorphic_op(e["XA"], R, t)]
    ok4 = check("control: rotation-with-fractional-translation SUCCEEDS (4_2 screw among exchanging ops)", len(four) > 0)
    ok5 = check("control verdict: ALTERMAGNETIC-ALLOWED", e["verdict"].startswith("ALTERMAGNETIC"))
    # with the actual spins as axial vectors: magnetic structure is invariant under screw x time reversal
    up, dn = ("ax", vec(0,0,1)), ("ax", vec(0,0,-1))
    Smag = Structure([], [(vec(0,0,0), up), (vec(F(1,2),F(1,2),F(1,2)), dn)] + X)
    Srev = Structure([], [(vec(0,0,0), dn), (vec(F(1,2),F(1,2),F(1,2)), up)] + X)
    body = vec(F(1,2),F(1,2),F(1,2))
    ok6 = check("control with explicit axial spins: {C4z|1/2,1/2,1/2} maps structure to its time-reverse; "
                "pure translation does not; no inversion does",
                Smag.maps_to(C4z, body, Srev) and not Smag.maps_to(I3, body, Srev)
                and not any(R == MINUS_I3 for R, t in Smag.ops_onto(D4H, Srev)))
    print("\n  Negative control 1: same Mn lattice, anions removed (bare BCT antiferromagnet).")
    e1 = exchange_analysis("bare BCT AFM", [], [], A, B, D4H)
    ok7 = check("negative control 1 returns DEGENERATE (translation)", e1["verdict"].startswith("DEGENERATE (translation)"))
    print("\n  Negative control 2: magnetic sites on the two tet sublattices of FCC (inversion partners).")
    e2 = exchange_analysis("FCC tet-site AFM", FCC, [(vec(0,0,0), "S")],
                           [(vec(F(1,4),F(1,4),F(1,4)), "T")], [(vec(F(3,4),F(3,4),F(3,4)), "T")], OH)
    ok8 = check("negative control 2 returns DEGENERATE (inversion)", e2["verdict"].startswith("DEGENERATE (inversion)"))
    return all([ok1, ok2, ok3, ok4, ok5, ok6, ok7, ok8])


# --------------------------------------------------------------------------
# NEARMISS  section-4 derivations. Each block builds ONLY what the cited corpus
# passage states (sites, labels); nothing is added, tuned or invented.
# Frame: tetragonal conventional cell, fractional coordinates; spheres at
# (0,0,0) [corner, "A"] and (1/2,1/2,1/2) [body centre, "B"].
# "generic c/a": candidate point operations D4h (holohedry of a tetragonal metric).
# "c/a = sqrt2": candidate point operations O_h written in the same frame (CHECK 1
# proves the metric is cubic there).
# --------------------------------------------------------------------------
H = F(1, 2); Q = F(1, 4)
BODY = vec(H, H, H)
SPH_A, SPH_B = vec(0, 0, 0), BODY
OCT_T = [vec(H, H, 0), vec(0, 0, H)]                 # App D.1 / Monograph: V_oct = (1/2,1/2,0); + body-centring image
TET1 = [vec(H, 0, Q), vec(0, H, 3*Q)]                # App D.1: V_tet = (1/2,0,gamma/4), and its body-centring image
TET2 = [vec(0, H, Q), vec(H, 0, 3*Q)]                # the C4 image (App Q.5: "related by the C4v rotation")
MZ = mat([[1,0,0],[0,1,0],[0,0,-1]]); MX = mat([[-1,0,0],[0,1,0],[0,0,1]]); MD = mat([[0,1,0],[1,0,0],[0,0,1]])

def describe(name, cent, sites, pointops, list_ops=True):
    """Full surviving operation set (printed as coordinate triplets) + the fingerprint used to name the space group.
       Tetragonal groups are printed in the tetragonal frame; cubic groups are converted exactly to the cubic frame
       (x,y,z)_c = M (x,y,z)_t and reduced modulo the face-centring translations, so that they can be read against
       International Tables directly."""
    g = full_group(name, cent, sites, pointops, list_ops=False)
    S = g["S"]; ops = g["ops"]
    lattice = "I" if BODY in S.translation_cosets() else "P"
    assert len(S.translation_cosets()) == (2 if lattice == "I" else 1)
    def status(R):
        hit = [(r, t) for r, t in ops if r == R]
        if not hit: return "absent"
        return "glide/screw" if is_nonsymmorphic_op(S, *hit[0]) else "point-type"
    fp = dict(lattice=lattice, pg=g["pg"], n=len(ops), nonsym=g["nonsym"],
              four=status(C4z), two_a=status(C2x), m_c=status(MZ), m_a=status(MX), m_d=status(MD),
              inv="present" if any(R == MINUS_I3 for R, _ in ops) else "absent",
              body_translation=S.maps_to(I3, BODY))
    cubic = g["pg"].split()[0] in ("Oh", "O", "Td", "Th", "T")
    if cubic:
        cos = [vec(0,0,0)] + FCC
        trip = sorted({triplet(mm(M_T2C, mm(R, M_C2T)), min(mod1(vadd(mv(M_T2C, t), c)) for c in cos)) for R, t in ops})
        frame = "cubic frame, modulo F-centring (0,0,0; 0,1/2,1/2; 1/2,0,1/2; 1/2,1/2,0)"
    else:
        trip = sorted(triplet(R, t) for R, t in ops)
        frame = "tetragonal frame" + (", modulo I-centring (0,0,0; 1/2,1/2,1/2)" if lattice == "I" else ", primitive lattice")
    OPSETS[name] = dict(frame=frame, ops=trip, fingerprint={k: str(v) for k, v in fp.items()})
    if list_ops:
        print(f"    surviving operations ({len(trip)}; {frame}):")
        for k in range(0, len(trip), 4):
            print("      " + "   ".join(f"{x:24s}" for x in trip[k:k+4]).rstrip())
    print(f"    fingerprint: lattice {fp['lattice']} (tetragonal description); point group {fp['pg']}; {fp['n']} ops; "
          f"screw/glide ops {fp['nonsym']}; 4-fold about c {fp['four']}; 2 along a {fp['two_a']}; plane normal to c {fp['m_c']}; "
          f"normal to a {fp['m_a']}; normal to [110] {fp['m_d']}; inversion {fp['inv']}")
    print(f"    corner -> body-centre by the PURE translation (1/2,1/2,1/2) is a symmetry of this decorated structure: "
          f"{'YES' if fp['body_translation'] else 'NO'}")
    return g, fp

def nearmiss():
    sph = [(SPH_A, "S")]            # with BCT centring both corner and body-centre spheres are generated
    # ---------------------------------------------------------------- NM-1
    section("NM-1  App K sec.1.1 / Letter 27 / App AZ7: 'A sublattice = corners, B sublattice = body centres' "
            "(bipartite labels; 8 A-B bonds)")
    print("  Decorated structure as written: identical sites; A at (n1,n2,n3) , B at (n1+1/2,n2+1/2,n3+1/2);")
    print("  only the 8 bonds delta = (+-1/2,+-1/2,+-1/2) are declared. Two readings, both derived.")
    print("  (i) labels only (no physical difference between A and B):")
    e = exchange_analysis("NM-1(i) generic c/a", [], [], [(SPH_A, "S")], [(SPH_B, "S")], D4H)
    check("NM-1(i): A and B exchanged by a pure translation -> DEGENERATE", e["a"] != [])
    g, fp = describe("NM-1(i) generic c/a: bare BCT", BCT, sph, D4H)
    check("NM-1(i) generic c/a: I lattice, D4h, symmorphic -> I4/mmm (No. 139)",
          fp["pg"].startswith("D4h") and fp["nonsym"] == 0 and fp["body_translation"] and fp["n"] == 16)
    g, fp = describe("NM-1(i) c/a = sqrt2: bare BCT = FCC", BCT, sph, OH_T)
    check("NM-1(i) c/a = sqrt2: O_h, symmorphic, 48 ops per primitive cell -> Fm-3m (No. 225)",
          fp["pg"].startswith("Oh") and fp["nonsym"] == 0 and fp["n"] == 48)
    print("  (ii) the 8 declared A-B bonds kept as a decoration (bond midpoints marked), in-plane A-A contacts unmarked:")
    bonds = [(vec(Q, Q, Q), "bond"), (vec(3*Q, Q, Q), "bond"), (vec(Q, 3*Q, Q), "bond"), (vec(3*Q, 3*Q, Q), "bond")]
    g, fp = describe("NM-1(ii) c/a = sqrt2, O_h candidates", BCT, sph + bonds, OH_T)
    check("NM-1(ii): marking only the 8 A-B bonds lowers Fm-3m to I4/mmm (No. 139) even at sqrt2, "
          "and the body-centring translation survives",
          fp["pg"].startswith("D4h") and fp["nonsym"] == 0 and fp["n"] == 16 and fp["body_translation"])
    e = exchange_analysis("NM-1(ii) A vs B with bonds as host", [], [(p, l) for p, l in Structure(BCT, bonds).pts.items()],
                          [(SPH_A, "S")], [(SPH_B, "S")], OH_T)
    check("NM-1(ii): A and B still exchanged by a pure translation -> DEGENERATE", e["a"] != [])

    # ---------------------------------------------------------------- NM-2
    section("NM-2  App L sec.4.3: 'right-handed on A, left-handed on B' (staggered Weyl components)")
    print("  Decorated structure as written: A = corners carry handedness R, B = body centres carry L. No positions,")
    print("  vectors or axes beyond that. Handedness is a pseudoscalar (+1 / -1): it changes sign under improper operations.")
    R_, L_ = ("ps", F(1)), ("ps", F(-1))
    nm2 = [(SPH_A, R_), (SPH_B, L_)]
    print("  Bare site sets (ignoring the label): related by the pure translation (1/2,1/2,1/2) -- see NM-1(i).")
    for tag, ops_ in (("generic c/a", D4H), ("c/a = sqrt2", OH_T)):
        e = exchange_analysis(f"NM-2 {tag}: R-sites vs L-sites, label transforming as a pseudoscalar", [], [],
                              [(SPH_A, R_)], [(SPH_B, L_)], ops_)
        check(f"NM-2 {tag}: no pure translation maps the R sublattice onto the L sublattice with labels respected", e["a"] == [])
        check(f"NM-2 {tag}: inversion (centre (1/4,1/4,1/4)) DOES -> DEGENERATE (inversion)",
              e["b"] != [] and e["verdict"].startswith("DEGENERATE (inversion)"))
        g, fp = describe(f"NM-2 {tag}: handedness as pseudoscalar", [], nm2, ops_)
        check(f"NM-2 {tag}: P lattice, D4h, 16 ops; 4 and 2(a) point-type; planes normal to c, a and [110] all glides; "
              f"inversion present; body-centring demoted from translation -> P4/nnc (No. 126), sites on 2a (422)",
              fp["lattice"] == "P" and fp["pg"].startswith("D4h") and fp["n"] == 16 and fp["four"] == "point-type"
              and fp["two_a"] == "point-type" and fp["m_c"] == fp["m_a"] == fp["m_d"] == "glide/screw"
              and fp["inv"] == "present" and not fp["body_translation"])
        S = g["S"]
        four_screw = [1 for R, t in g["ops"] if op_type(R) == "4" and is_nonsymmorphic_op(S, R, t)]
        check(f"NM-2 {tag}: there is NO 4_2 (or any) screw axis along c: every 4-fold operation is point-type",
              four_screw == [])
    print("  Alternative reading (R and L as two plain colours, no pseudoscalar character; this is also the structure")
    print("  described by the sublattice sign operators sigma_z (App L sec.1) and Gamma = diag(+1,-1) (App N sec.N.3.1)):")
    g, fp = describe("NM-2 alt: two scalar labels", [], [(SPH_A, "R"), (SPH_B, "L")], OH_T)
    check("NM-2 alt: P lattice, D4h, symmorphic -> P4/mmm (No. 123) (CuAu-I / L1_0 type ordering); "
          "then no operation exchanges the two labels at all",
          fp["lattice"] == "P" and fp["pg"].startswith("D4h") and fp["nonsym"] == 0 and fp["n"] == 16)

    print("  The formula written in the same passage, eta_stag = sum over k in {0,1}^3 of (-1)^(k1+k2+k3):")
    ks = list(product((0, 1), repeat=3))
    check("NM-2: the eight signs sum to zero, as the source states", sum((-1) ** (a + b + c) for a, b, c in ks) == 0)
    print("    read on the two actual sites of the cell (k = 000 at the corner, k = 111 at the body centre, in half-cell")
    print(f"    units) it gives sign {(-1)**0:+d} on A and {(-1)**3:+d} on B: the two-colour reading just derived.")
    print("    read instead as a checkerboard sign (-1)^(n1+n2+n3) on the corner lattice alone (the source gives no")
    print("    value for body centres in that reading): doubled cell 2a x 2a x 2c, like signs on an F-centred lattice.")
    e = exchange_analysis("NM-2 checkerboard reading: + sites vs - sites", FCC, [], [(vec(0, 0, 0), "s")], [(vec(H, 0, 0), "s")], D4H)
    check("NM-2 checkerboard reading: + and - sites are exchanged by a pure translation -> DEGENERATE", e["a"] != [])
    gcb = full_group("NM-2 checkerboard reading, two colours", FCC, [(vec(0, 0, 0), "+"), (vec(H, 0, 0), "-")], D4H)
    check("NM-2 checkerboard reading: F-centred tetragonal cell, D4h, symmorphic -> F4/mmm, i.e. I4/mmm (No. 139) "
          "in its standard cell",
          gcb["pg"].startswith("D4h") and gcb["nonsym"] == 0 and len(gcb["ops"]) == 16 and len(gcb["S"].translation_cosets()) == 4)

    # ---------------------------------------------------------------- NM-3
    section("NM-3  App D.1 sec.3 / Monograph sec.2 / OneMedium: oct void 'corner group' vs 'body-centre group';  "
            "Letter 127: 'octahedral void has a preferred orientation (the z-axis)'")
    print("  Decorated structure as written: each oct void carries a distinguished axis along c (its two axial")
    print("  neighbours vs its four equatorial neighbours). Modelled as a director (headless axis) (0,0,1) on every oct void.")
    dz = ("dir", vec(0, 0, 1))
    octs = [(OCT_T[0], dz)]
    e = exchange_analysis("NM-3 c/a = sqrt2: oct void (1/2,1/2,0) vs oct void (0,0,1/2), directors along c",
                          [], [(SPH_A, "S"), (SPH_B, "S")], [(OCT_T[0], dz)], [(OCT_T[1], dz)], OH_T)
    check("NM-3: the two oct voids of the cell, with their c-directors, are exchanged by a pure translation -> DEGENERATE",
          e["a"] != [])
    g, fp = describe("NM-3 c/a = sqrt2, O_h candidates", BCT, sph + octs, OH_T)
    check("NM-3: a c-director on every oct void lowers Fm-3m to I4/mmm (No. 139); symmorphic; body-centring translation survives",
          fp["pg"].startswith("D4h") and fp["nonsym"] == 0 and fp["n"] == 16 and fp["body_translation"])
    print("  Who is 'corner' and who is 'body centre' around each void:")
    eq1 = sorted(mod1(vadd(OCT_T[0], d)) for d in (vec(H,H,0), vec(-H,H,0), vec(H,-H,0), vec(-H,-H,0)))
    ax1 = sorted(mod1(vadd(OCT_T[0], d)) for d in (vec(0,0,H), vec(0,0,-H)))
    eq2 = sorted(mod1(vadd(OCT_T[1], d)) for d in (vec(H,H,0), vec(-H,H,0), vec(H,-H,0), vec(-H,-H,0)))
    ax2 = sorted(mod1(vadd(OCT_T[1], d)) for d in (vec(0,0,H), vec(0,0,-H)))
    print(f"    void (1/2,1/2,0): equatorial neighbours {sorted(set(map(fmt_v, eq1)))}  axial {sorted(set(map(fmt_v, ax1)))}")
    print(f"    void (0,0,1/2)  : equatorial neighbours {sorted(set(map(fmt_v, eq2)))}  axial {sorted(set(map(fmt_v, ax2)))}")
    check("NM-3: around void (1/2,1/2,0) the equatorial four are corners and the axial two are body centres; around void "
          "(0,0,1/2) the roles are swapped -- i.e. the two pictures are images under the body-centring translation",
          set(eq1) == {SPH_A} and set(ax1) == {SPH_B} and set(eq2) == {SPH_B} and set(ax2) == {SPH_A})

    # ---------------------------------------------------------------- NM-4
    section("NM-4  oct voids vs tet voids given different labels: App D.3 sec.4.2 ('tet and oct voids alternate'), "
            "Letter 30 (u on oct, d on tet), App Y (left-handed oct doublet / right-handed tet component), "
            "Letter 62 (OHC in oct voids, TVC in tet voids), App BK and Vol.1 Part 2 p.342 (u/d vs tet/oct, reversed), "
            "Vol.2 ('tetrahedral void is the parity-odd void'), WikiChallenge (oct left-handed, tet right-handed)")
    print("  Decorated structure as written: label X on every oct void, label Y on every tet void (both tet sets alike).")
    tets = [(TET1[0], "Y"), (TET2[0], "Y")]
    print(f"  per primitive cell: {len(Structure(BCT, [(OCT_T[0], 'X')]).pts)//2} oct void, "
          f"{len(Structure(BCT, tets).pts)//2} tet voids")
    e = exchange_analysis("NM-4 c/a = sqrt2: oct set vs one tet set (spheres + other tet set as host)",
                          BCT, sph + [(TET2[0], "Y")], [(OCT_T[0], "V")], [(TET1[0], "V")], OH_T)
    check("NM-4: NO operation of any kind exchanges the oct sublattice with a tet sublattice (inequivalent sites)", e["swap"] == [])
    g, fp = describe("NM-4 scalar labels, c/a = sqrt2", BCT, sph + [(OCT_T[0], "X")] + tets, OH_T)
    check("NM-4 (scalar labels / occupancy): Fm-3m (No. 225) unchanged; body-centring translation survives",
          fp["pg"].startswith("Oh") and fp["nonsym"] == 0 and fp["n"] == 48 and fp["body_translation"])
    g, fp = describe("NM-4 scalar labels, generic c/a", BCT, sph + [(OCT_T[0], "X")] + tets, D4H)
    check("NM-4 (scalar labels), generic c/a: I4/mmm (No. 139)", fp["pg"].startswith("D4h") and fp["nonsym"] == 0 and fp["n"] == 16)
    hand = sph + [(OCT_T[0], ("ps", F(-1)))] + [(TET1[0], ("ps", F(1))), (TET2[0], ("ps", F(1)))]
    g, fp = describe("NM-4 handedness as pseudoscalar (oct L, all tets R), c/a = sqrt2", BCT, hand, OH_T)
    check("NM-4 (handedness as pseudoscalar): only the 24 proper operations survive, symmorphic -> F432 (No. 209); "
          "body-centring translation survives",
          fp["pg"].startswith("O (432)") and fp["nonsym"] == 0 and fp["n"] == 24 and fp["body_translation"])
    g, fp = describe("NM-4 handedness as pseudoscalar, generic c/a", BCT, hand, D4H)
    check("NM-4 (handedness as pseudoscalar), generic c/a: I422 (No. 97)",
          fp["pg"].startswith("D4 (422)") and fp["nonsym"] == 0 and fp["n"] == 8)

    # ---------------------------------------------------------------- NM-5
    section("NM-5  App Q.5: '2 tetrahedral voids (up-type and down-type) ... 2 per unit cell, related by the C4v rotation'; "
            "Vol.2 p.333: 'two tetrahedral voids per BCT unit cell (above and below the ab-plane)'")
    print("  Decorated structure as written: tet set T1 = (1/2,0,1/4)+BCT, tet set T2 = (0,1/2,1/4)+BCT (the C4 image).")
    check("NM-5: C4 about c through a sphere maps T1 onto T2", {mod1(mv(C4z, p)) for p in TET1} == set(TET2))
    check("NM-5: the mirror z -> -z through a sphere ('above and below the ab-plane') also maps T1 onto T2",
          {mod1(mv(MZ, p)) for p in TET1} == set(TET2))
    for tag, ops_ in (("generic c/a", D4H), ("c/a = sqrt2", OH_T)):
        e = exchange_analysis(f"NM-5 {tag}: T1 vs T2 (spheres as host)", BCT, sph, [(TET1[0], "T")], [(TET2[0], "T")], ops_)
        check(f"NM-5 {tag}: T1 and T2 are NOT related by a pure translation", e["a"] == [])
        check(f"NM-5 {tag}: they ARE related by inversion -> DEGENERATE (inversion)", e["b"] != [] and e["verdict"].startswith("DEGENERATE (inversion)"))
        check(f"NM-5 {tag}: they are also related by 4-fold rotations, all point-type (no screw)",
              any(op_type(R) == "4" for R, t in e["c"]) and not any(op_type(R) == "4" and is_nonsymmorphic_op(e["XA"], R, t) for R, t in e["c"]))
    g, fp = describe("NM-5 both tet sets alike, generic c/a", BCT, sph + [(TET1[0], "T"), (TET2[0], "T")], D4H)
    check("NM-5 (T1, T2 alike), generic c/a: I4/mmm (No. 139), tets on 4d", fp["pg"].startswith("D4h") and fp["nonsym"] == 0 and fp["n"] == 16)
    g, fp = describe("NM-5 both tet sets alike, c/a = sqrt2", BCT, sph + [(TET1[0], "T"), (TET2[0], "T")], OH_T)
    check("NM-5 (T1, T2 alike), c/a = sqrt2: Fm-3m (No. 225), tets on 8c", fp["pg"].startswith("Oh") and fp["nonsym"] == 0 and fp["n"] == 48)
    g, fp = describe("NM-5 T1 = 'up-type', T2 = 'down-type' as distinct scalar labels, generic c/a", BCT,
                     sph + [(TET1[0], "Tu"), (TET2[0], "Td")], D4H)
    check("NM-5 (distinct labels), generic c/a: I lattice, D2d, symmorphic, mirrors normal to a kept, diagonal mirrors lost "
          "-> I-4m2 (No. 119); body-centring translation survives",
          fp["pg"].startswith("D2d") and fp["nonsym"] == 0 and fp["n"] == 8 and fp["m_a"] == "point-type"
          and fp["m_d"] == "absent" and fp["body_translation"])
    g, fp = describe("NM-5 distinct scalar labels, c/a = sqrt2", BCT, sph + [(TET1[0], "Tu"), (TET2[0], "Td")], OH_T)
    check("NM-5 (distinct labels), c/a = sqrt2: F lattice, T_d, symmorphic -> F-43m (No. 216); body-centring translation survives",
          fp["pg"].startswith("Td") and fp["nonsym"] == 0 and fp["n"] == 24 and fp["body_translation"])

    # ---------------------------------------------------------------- summary
    section("NEAR-MISS SUMMARY: is the corner -> body-centre operation ever a screw or glide that is not reducible "
            "to a translation or an inversion?")
    print("  NM-1  translation                       -> degenerate")
    print("  NM-2  inversion (translation for bare sites); glides present but inversion present too; no screw -> degenerate")
    print("  NM-3  translation                       -> degenerate")
    print("  NM-4  translation (oct/tet never exchanged by anything) -> not a compensated pair")
    print("  NM-5  translation for the spheres; T1<->T2 by inversion -> degenerate")

# --------------------------------------------------------------------------
# CROSSCHECK (non-gating)  compare every operation set found above with the
# tabulated general positions of the named space group, taken from the spglib
# database (Hall-symbol tables, which reproduce International Tables Vol. A).
# Optional: needs `pip install spglib`. It is reported separately and is NOT
# counted among the exact-arithmetic assertions, because the database stores
# its translations as floats (0.25, 0.5 ...; converted here to rationals).
# --------------------------------------------------------------------------
def crosscheck():
    section("CROSSCHECK (non-gating)  operation sets vs tabulated space-group operations (spglib database)")
    try:
        import spglib
    except Exception as ex:                                   # pragma: no cover
        print(f"  spglib not available ({ex.__class__.__name__}); cross-check skipped. The exact checks above do not depend on it.")
        return
    def db(hall):
        d = spglib.get_symmetry_from_database(hall)
        return [(mat([[int(x) for x in r] for r in R]), tuple(F(float(x)).limit_denominator(24) for x in t))
                for R, t in zip(d["rotations"], d["translations"])]
    def canon(t, cosets): return min(mod1(vadd(t, c)) for c in cosets)
    FCC_COS = [vec(0,0,0)] + FCC
    def compare(label, hall, sites, cent, pointops, cubic=False):
        S = Structure(cent, sites); mine = S.ops_onto(pointops)
        if cubic:      # my structures live in the tetragonal frame; the table is in the cubic frame
            mine_c = {(mm(M_T2C, mm(R, M_C2T)), canon(mv(M_T2C, t), FCC_COS)) for R, t in mine}
            tab = {(R, canon(t, FCC_COS)) for R, t in db(hall)}
        else:
            mine_c = {(R, S.canon_t(t)) for R, t in mine}
            tab = {(R, S.canon_t(t)) for R, t in db(hall)}
        ty = spglib.get_spacegroup_type(hall)
        ok = mine_c == tab
        print(f"  {'MATCH   ' if ok else 'MISMATCH'}  {label}: {len(mine_c)} ops found vs {len(tab)} tabulated for "
              f"{ty.international_full.strip()} (No. {ty.number}{', origin choice ' + ty.choice if ty.choice else ''}, Hall {hall})")
        return ok
    u = F(61, 200); A, B, X = rutile_sites(u)
    sph = [(SPH_A, "S")]
    R_, L_ = ("ps", F(1)), ("ps", F(-1))
    res = [
      compare("control MnF2 (rutile)", 419, A + B + X, [], D4H),
      compare("NM-1(i)/NM-5 bare BCT, generic c/a", 424, sph, BCT, D4H),
      compare("NM-1(i) bare BCT at c/a = sqrt2", 523, sph, BCT, OH_T, cubic=True),
      compare("NM-2 handedness staggered (pseudoscalar), generic c/a", 404, [(SPH_A, R_), (SPH_B, L_)], [], D4H),
      compare("NM-2 handedness staggered (pseudoscalar), c/a = sqrt2", 404, [(SPH_A, R_), (SPH_B, L_)], [], OH_T),
      compare("NM-2 alt two scalar labels", 400, [(SPH_A, "R"), (SPH_B, "L")], [], OH_T),
      compare("NM-3 c-director on oct voids, c/a = sqrt2", 424, sph + [(OCT_T[0], ("dir", vec(0,0,1)))], BCT, OH_T),
      compare("NM-4 scalar labels, c/a = sqrt2", 523, sph + [(OCT_T[0], "X"), (TET1[0], "Y"), (TET2[0], "Y")], BCT, OH_T, cubic=True),
      compare("NM-4 pseudoscalar handedness, c/a = sqrt2", 505,
              sph + [(OCT_T[0], L_), (TET1[0], R_), (TET2[0], R_)], BCT, OH_T, cubic=True),
      compare("NM-4 pseudoscalar handedness, generic c/a", 374,
              sph + [(OCT_T[0], L_), (TET1[0], R_), (TET2[0], R_)], BCT, D4H),
      compare("NM-5 distinct tet labels, generic c/a", 396, sph + [(TET1[0], "Tu"), (TET2[0], "Td")], BCT, D4H),
      compare("NM-5 distinct tet labels, c/a = sqrt2", 512, sph + [(TET1[0], "Tu"), (TET2[0], "Td")], BCT, OH_T, cubic=True),
    ]
    print(f"  cross-check: {sum(res)} / {len(res)} operation sets identical to the tabulated group")
    # independent structure-level identification for the scalar-labelled structures (floating point inside spglib)
    try:
        import numpy as np
        def ident(label, sites, cent, c_over_a):
            S = Structure(cent, sites); labs = sorted({str(l) for l in S.pts.values()})
            pos = [[float(x) for x in p] for p in S.pts]; num = [labs.index(str(l)) + 1 for l in S.pts.values()]
            cell = (np.diag([1.0, 1.0, c_over_a]), pos, num)
            print(f"  spglib.get_spacegroup  {label:58s} -> {spglib.get_spacegroup(cell, symprec=1e-6)}")
        r2 = 2 ** 0.5
        ident("control MnF2 (c/a = 0.68 as in the real crystal)", A + B + X, [], 0.68)
        ident("bare BCT, c/a = 1.2 (generic)", sph, BCT, 1.2)
        ident("bare BCT, c/a = sqrt2", sph, BCT, r2)
        ident("NM-2 alt two scalar labels, c/a = sqrt2", [(SPH_A, 'R'), (SPH_B, 'L')], [], r2)
        ident("NM-4 scalar labels, c/a = sqrt2", sph + [(OCT_T[0], 'X'), (TET1[0], 'Y'), (TET2[0], 'Y')], BCT, r2)
        ident("NM-5 distinct tet labels, c/a = 1.2", sph + [(TET1[0], 'Tu'), (TET2[0], 'Td')], BCT, 1.2)
        ident("NM-5 distinct tet labels, c/a = sqrt2", sph + [(TET1[0], 'Tu'), (TET2[0], 'Td')], BCT, r2)
        ident("NM-3 c-axis marked on oct voids by two satellites, sqrt2",
              sph + [(vec(H, H, F(1,10)), 'm'), (vec(H, H, F(-1,10)), 'm')], BCT, r2)
    except Exception as ex:                                   # pragma: no cover
        print(f"  structure-level identification skipped ({ex.__class__.__name__}: {ex})")

def main():
    check1(); check2(); check3(); check4()
    ctrl = control()
    print("\n  POSITIVE CONTROL:", "PASSED" if ctrl else "FAILED  -> SC-R-1")
    nearmiss()
    crosscheck()
    if "--dump" in sys.argv:
        import json
        with open(sys.argv[sys.argv.index("--dump") + 1], "w") as fh: json.dump(OPSETS, fh, indent=1)
    section("SUMMARY")
    bad = [l for l, ok in RESULTS if not ok]
    print(f"  {len(RESULTS) - len(bad)} / {len(RESULTS)} assertions passed")
    for l in bad: print("  FAILED:", l)
    sys.exit(0 if not bad else 1)

if __name__ == "__main__":
    main()
